package com.supermartijn642.packedup.generators;

import com.supermartijn642.core.data.condition.NotResourceCondition;
import com.supermartijn642.core.generator.RecipeGenerator;
import com.supermartijn642.core.generator.ResourceCache;
import com.supermartijn642.packedup.BackpackRecipeCondition;
import com.supermartijn642.packedup.BackpackType;
import com.supermartijn642.packedup.BackpackUpgradeRecipe;
import com.supermartijn642.packedup.PackedUp;
import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.Tags;

/**
 * Created 14/11/2022 by SuperMartijn642
 */
public class PackedUpRecipeGenerator extends RecipeGenerator {

    public PackedUpRecipeGenerator(ResourceCache cache){
        super("packedup", cache);
    }

    @Override
    public void generate(){
        // Basic
        this.shaped("basic_from_chest", PackedUp.basicbackpack)
            .pattern("ABA")
            .pattern("CDC")
            .pattern("CCC")
            .input('A', Tags.Items.RODS_WOODEN)
            .input('B', Tags.Items.STRING)
            .input('C', Tags.Items.LEATHER)
            .input('D', Tags.Items.CHESTS_WOODEN)
            .unlockedBy(Tags.Items.CHESTS_WOODEN)
            .condition(new BackpackRecipeCondition(BackpackType.BASIC));

        // Iron
        this.shaped("iron_from_chest", PackedUp.ironbackpack)
            .pattern("ABA")
            .pattern("CDC")
            .pattern("CCC")
            .input('A', Tags.Items.LEATHER)
            .input('B', Tags.Items.STRING)
            .input('C', Tags.Items.INGOTS_IRON)
            .input('D', Tags.Items.CHESTS_WOODEN)
            .unlockedBy(Tags.Items.CHESTS_WOODEN)
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.BASIC)))
            .condition(new BackpackRecipeCondition(BackpackType.IRON));
        this.shaped("iron_from_basic", PackedUp.ironbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.INGOTS_IRON)
            .input('B', Tags.Items.LEATHER)
            .input('C', PackedUp.basicbackpack)
            .unlockedBy(PackedUp.basicbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.BASIC))
            .condition(new BackpackRecipeCondition(BackpackType.IRON));

        // Copper
        this.shaped("copper_from_chest", PackedUp.copperbackpack)
            .pattern("ABA")
            .pattern("CDC")
            .pattern("CCC")
            .input('A', Tags.Items.LEATHER)
            .input('B', Tags.Items.STRING)
            .input('C', Tags.Items.INGOTS_COPPER)
            .input('D', Tags.Items.CHESTS_WOODEN)
            .unlockedBy(Tags.Items.CHESTS_WOODEN)
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.BASIC)))
            .condition(new BackpackRecipeCondition(BackpackType.COPPER));
        this.shaped("copper_from_basic", PackedUp.copperbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.INGOTS_COPPER)
            .input('B', Tags.Items.LEATHER)
            .input('C', PackedUp.basicbackpack)
            .unlockedBy(PackedUp.basicbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.BASIC))
            .condition(new BackpackRecipeCondition(BackpackType.COPPER));

        // Silver
        TagKey<Item> silverIngots = TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation("forge", "ingots/silver"));
        this.shaped("silver_from_chest", PackedUp.silverbackpack)
            .pattern("ABA")
            .pattern("CDC")
            .pattern("CCC")
            .input('A', Tags.Items.LEATHER)
            .input('B', Tags.Items.STRING)
            .input('C', silverIngots)
            .input('D', Tags.Items.CHESTS_WOODEN)
            .unlockedBy(Tags.Items.CHESTS_WOODEN)
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.BASIC)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new BackpackRecipeCondition(BackpackType.SILVER));
        this.shaped("silver_from_basic", PackedUp.silverbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', silverIngots)
            .input('B', Tags.Items.LEATHER)
            .input('C', PackedUp.basicbackpack)
            .unlockedBy(PackedUp.basicbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.BASIC))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new BackpackRecipeCondition(BackpackType.SILVER));
        this.shaped("silver_from_iron", PackedUp.silverbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', silverIngots)
            .input('B', Tags.Items.INGOTS_IRON)
            .input('C', PackedUp.ironbackpack)
            .unlockedBy(PackedUp.ironbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.IRON))
            .condition(new BackpackRecipeCondition(BackpackType.SILVER));
        this.shaped("silver_from_copper", PackedUp.silverbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', silverIngots)
            .input('B', Tags.Items.INGOTS_COPPER)
            .input('C', PackedUp.copperbackpack)
            .unlockedBy(PackedUp.copperbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.COPPER))
            .condition(new BackpackRecipeCondition(BackpackType.SILVER));

        // Gold
        this.shaped("gold_from_chest", PackedUp.goldbackpack)
            .pattern("ABA")
            .pattern("CDC")
            .pattern("CCC")
            .input('A', Tags.Items.LEATHER)
            .input('B', Tags.Items.STRING)
            .input('C', Tags.Items.INGOTS_GOLD)
            .input('D', Tags.Items.CHESTS_WOODEN)
            .unlockedBy(Tags.Items.CHESTS_WOODEN)
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.BASIC)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new BackpackRecipeCondition(BackpackType.GOLD));
        this.shaped("gold_from_basic", PackedUp.goldbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.INGOTS_GOLD)
            .input('B', Tags.Items.LEATHER)
            .input('C', PackedUp.basicbackpack)
            .unlockedBy(PackedUp.basicbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.BASIC))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new BackpackRecipeCondition(BackpackType.GOLD));
        this.shaped("gold_from_iron", PackedUp.goldbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.INGOTS_GOLD)
            .input('B', Tags.Items.INGOTS_IRON)
            .input('C', PackedUp.ironbackpack)
            .unlockedBy(PackedUp.ironbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.IRON))
            .condition(new BackpackRecipeCondition(BackpackType.GOLD));
        this.shaped("gold_from_copper", PackedUp.goldbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.INGOTS_GOLD)
            .input('B', Tags.Items.INGOTS_COPPER)
            .input('C', PackedUp.copperbackpack)
            .unlockedBy(PackedUp.copperbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.COPPER))
            .condition(new BackpackRecipeCondition(BackpackType.GOLD));

        // Diamond
        this.shaped("diamond_from_chest", PackedUp.diamondbackpack)
            .pattern("ABA")
            .pattern("CDC")
            .pattern("CEC")
            .input('A', Tags.Items.LEATHER)
            .input('B', Tags.Items.STRING)
            .input('C', Tags.Items.GEMS_DIAMOND)
            .input('D', Tags.Items.CHESTS_WOODEN)
            .input('E', Tags.Items.GLASS)
            .unlockedBy(Tags.Items.CHESTS_WOODEN)
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.BASIC)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new BackpackRecipeCondition(BackpackType.DIAMOND));
        this.shaped("diamond_from_basic", PackedUp.diamondbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("DDD")
            .input('A', Tags.Items.GEMS_DIAMOND)
            .input('B', Tags.Items.LEATHER)
            .input('C', PackedUp.basicbackpack)
            .input('D', Tags.Items.GLASS)
            .unlockedBy(PackedUp.basicbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.BASIC))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new BackpackRecipeCondition(BackpackType.DIAMOND));
        this.shaped("diamond_from_iron", PackedUp.diamondbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("DDD")
            .input('A', Tags.Items.GEMS_DIAMOND)
            .input('B', Tags.Items.INGOTS_IRON)
            .input('C', PackedUp.ironbackpack)
            .input('D', Tags.Items.GLASS)
            .unlockedBy(PackedUp.ironbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.IRON))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new BackpackRecipeCondition(BackpackType.DIAMOND));
        this.shaped("diamond_from_copper", PackedUp.diamondbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("DDD")
            .input('A', Tags.Items.GEMS_DIAMOND)
            .input('B', Tags.Items.INGOTS_COPPER)
            .input('C', PackedUp.copperbackpack)
            .input('D', Tags.Items.GLASS)
            .unlockedBy(PackedUp.copperbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.COPPER))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new BackpackRecipeCondition(BackpackType.DIAMOND));
        this.shaped("diamond_from_silver", PackedUp.diamondbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("DDD")
            .input('A', Tags.Items.GEMS_DIAMOND)
            .input('B', silverIngots)
            .input('C', PackedUp.silverbackpack)
            .input('D', Tags.Items.GLASS)
            .unlockedBy(PackedUp.silverbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.SILVER))
            .condition(new BackpackRecipeCondition(BackpackType.DIAMOND));
        this.shaped("diamond_from_gold", PackedUp.diamondbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("DDD")
            .input('A', Tags.Items.GEMS_DIAMOND)
            .input('B', Tags.Items.INGOTS_GOLD)
            .input('C', PackedUp.goldbackpack)
            .input('D', Tags.Items.GLASS)
            .unlockedBy(PackedUp.goldbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.GOLD))
            .condition(new BackpackRecipeCondition(BackpackType.DIAMOND));

        // Obsidian
        this.shaped("obsidian_from_chest", PackedUp.obsidianbackpack)
            .pattern("ABA")
            .pattern("CDC")
            .pattern("CCC")
            .input('A', Tags.Items.LEATHER)
            .input('B', Tags.Items.STRING)
            .input('C', Tags.Items.OBSIDIAN)
            .input('D', Tags.Items.CHESTS_WOODEN)
            .unlockedBy(Tags.Items.CHESTS_WOODEN)
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.BASIC)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.DIAMOND)))
            .condition(new BackpackRecipeCondition(BackpackType.OBSIDIAN));
        this.shaped("obsidian_from_basic", PackedUp.obsidianbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.OBSIDIAN)
            .input('B', Tags.Items.LEATHER)
            .input('C', PackedUp.basicbackpack)
            .unlockedBy(PackedUp.basicbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.BASIC))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.IRON)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.COPPER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.DIAMOND)))
            .condition(new BackpackRecipeCondition(BackpackType.OBSIDIAN));
        this.shaped("obsidian_from_iron", PackedUp.obsidianbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.OBSIDIAN)
            .input('B', Tags.Items.INGOTS_IRON)
            .input('C', PackedUp.ironbackpack)
            .unlockedBy(PackedUp.ironbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.IRON))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.DIAMOND)))
            .condition(new BackpackRecipeCondition(BackpackType.OBSIDIAN));
        this.shaped("obsidian_from_copper", PackedUp.obsidianbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.OBSIDIAN)
            .input('B', Tags.Items.INGOTS_COPPER)
            .input('C', PackedUp.copperbackpack)
            .unlockedBy(PackedUp.copperbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.COPPER))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.SILVER)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.GOLD)))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.DIAMOND)))
            .condition(new BackpackRecipeCondition(BackpackType.OBSIDIAN));
        this.shaped("obsidian_from_silver", PackedUp.obsidianbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.OBSIDIAN)
            .input('B', silverIngots)
            .input('C', PackedUp.silverbackpack)
            .unlockedBy(PackedUp.silverbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.SILVER))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.DIAMOND)))
            .condition(new BackpackRecipeCondition(BackpackType.OBSIDIAN));
        this.shaped("obsidian_from_gold", PackedUp.obsidianbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.OBSIDIAN)
            .input('B', Tags.Items.INGOTS_GOLD)
            .input('C', PackedUp.goldbackpack)
            .unlockedBy(PackedUp.goldbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.GOLD))
            .condition(new NotResourceCondition(new BackpackRecipeCondition(BackpackType.DIAMOND)))
            .condition(new BackpackRecipeCondition(BackpackType.OBSIDIAN));
        this.shaped("obsidian_from_diamond", PackedUp.obsidianbackpack)
            .customSerializer(BackpackUpgradeRecipe.SERIALIZER)
            .pattern("ABA")
            .pattern("ACA")
            .pattern("AAA")
            .input('A', Tags.Items.OBSIDIAN)
            .input('B', Tags.Items.GEMS_DIAMOND)
            .input('C', PackedUp.diamondbackpack)
            .unlockedBy(PackedUp.diamondbackpack)
            .condition(new BackpackRecipeCondition(BackpackType.DIAMOND))
            .condition(new BackpackRecipeCondition(BackpackType.OBSIDIAN));
    }
}
